"""
Train XGBoost model for SNBP acceptance probability prediction.

Reads prepared training data and trains a gradient boosting model that
captures non-linear patterns beyond the simple weighted formula.

IMPORTANT LIMITATION: The training data is synthetic, generated by the
deterministic formula (from predict.php) plus Gaussian noise and minor
interaction terms. As a result, this model approximates the formula rather
than learning from real admission outcomes. The reported R2 metric reflects
how well the model reproduces the formula, not predictive power against
actual SNBP admission results.

With real admission outcome data (accepted/rejected per student per program),
this model could be retrained to learn genuine patterns that the formula
cannot capture. Until then, the model serves as a smoothed, non-linear
approximation that provides confidence intervals and feature importances.
"""

import os
import sys

import joblib
import numpy as np
import pandas as pd
from sklearn.model_selection import cross_val_score, train_test_split
from sklearn.metrics import mean_absolute_error, mean_squared_error, r2_score

try:
    from xgboost import XGBRegressor
    USE_XGBOOST = True
except ImportError:
    from sklearn.ensemble import GradientBoostingRegressor
    USE_XGBOOST = False
    print("WARNING: XGBoost not available, using sklearn GradientBoostingRegressor")

# Paths
TRAINING_DATA_PATH = os.path.join(
    os.path.dirname(os.path.abspath(__file__)),
    "training_data.csv",
)

MODEL_OUTPUT_PATH = os.path.join(
    os.path.dirname(os.path.dirname(os.path.abspath(__file__))),
    "models",
    "prediction_model.joblib",
)

# Features used by the model
FEATURE_COLS = [
    "avg_score",
    "ranking_percentile",
    "accred_score",
    "competition_ratio",
    "applicant_trend",
    "daya_tampung",
]

TARGET_COL = "probability"


def load_data(data_path: str) -> pd.DataFrame:
    """Load training data from CSV."""
    if not os.path.exists(data_path):
        print(f"ERROR: Training data not found at {data_path}")
        print("Run prepare_data.py first to generate training data.")
        sys.exit(1)

    df = pd.read_csv(data_path)
    print(f"Loaded {len(df)} training samples with {len(df.columns)} columns")
    return df


def train_model(df: pd.DataFrame):
    """Train the prediction model."""
    X = df[FEATURE_COLS].values
    y = df[TARGET_COL].values

    # Train/test split
    X_train, X_test, y_train, y_test = train_test_split(
        X, y, test_size=0.2, random_state=42
    )

    print(f"Training set: {len(X_train)} samples")
    print(f"Test set: {len(X_test)} samples")

    # Create model
    if USE_XGBOOST:
        model = XGBRegressor(
            n_estimators=200,
            max_depth=6,
            learning_rate=0.1,
            subsample=0.8,
            colsample_bytree=0.8,
            reg_alpha=0.1,
            reg_lambda=1.0,
            random_state=42,
            verbosity=0,
        )
        print("\nTraining XGBoost model...")
    else:
        model = GradientBoostingRegressor(
            n_estimators=200,
            max_depth=6,
            learning_rate=0.1,
            subsample=0.8,
            random_state=42,
        )
        print("\nTraining GradientBoosting model...")

    # Fit model
    model.fit(X_train, y_train)

    # Evaluate on test set
    y_pred = model.predict(X_test)
    y_pred = np.clip(y_pred, 0.05, 0.95)

    mae = mean_absolute_error(y_test, y_pred)
    mse = mean_squared_error(y_test, y_pred)
    rmse = np.sqrt(mse)
    r2 = r2_score(y_test, y_pred)

    print(f"\nTest Set Metrics:")
    print(f"  MAE:  {mae:.4f}")
    print(f"  RMSE: {rmse:.4f}")
    print(f"  R2:   {r2:.4f}")

    # Cross-validation
    print("\nCross-validation (5-fold)...")
    cv_scores = cross_val_score(model, X, y, cv=5, scoring="r2")
    print(f"  CV R2 scores: {cv_scores}")
    print(f"  CV R2 mean:   {cv_scores.mean():.4f} (+/- {cv_scores.std() * 2:.4f})")

    # Feature importances
    if USE_XGBOOST:
        importances = model.feature_importances_
    else:
        importances = model.feature_importances_

    print(f"\nFeature Importances:")
    for name, imp in sorted(
        zip(FEATURE_COLS, importances), key=lambda x: x[1], reverse=True
    ):
        print(f"  {name:25s}: {imp:.4f}")

    return model


def save_model(model, output_path: str):
    """Save trained model to disk."""
    os.makedirs(os.path.dirname(output_path), exist_ok=True)
    joblib.dump(model, output_path)
    file_size = os.path.getsize(output_path) / 1024
    print(f"\nModel saved to: {output_path} ({file_size:.1f} KB)")


def main():
    """Main entry point for model training."""
    print("=" * 60)
    print("LangkahKampus - ML Model Training")
    print("=" * 60)

    # Load data
    df = load_data(TRAINING_DATA_PATH)

    # Validate data
    print(f"\nTarget distribution:")
    print(f"  Min:    {df[TARGET_COL].min():.4f}")
    print(f"  Max:    {df[TARGET_COL].max():.4f}")
    print(f"  Mean:   {df[TARGET_COL].mean():.4f}")
    print(f"  Median: {df[TARGET_COL].median():.4f}")

    # Train
    model = train_model(df)

    # Save
    save_model(model, MODEL_OUTPUT_PATH)

    print("\n" + "=" * 60)
    print("Training complete!")
    print("=" * 60)


if __name__ == "__main__":
    main()
